#!/bin/bash
set -e
set -x

source $(dirname $0)/version
cd $(dirname $0)/..

ARTIFACTS=$(pwd)/dist/artifacts
CD=${BUILD}/cd
rm -rf ${CD}/
ISO=${ARTIFACTS}/$(echo ${DISTRIB_ID} | tr '[:upper:]' '[:lower:]').iso

mkdir -p ${CD}/boot/isolinux
mkdir -p ${CD}/rancheros

mkdir -p ${CD}/boot
cp ${ARTIFACTS}/${INITRD}                     ${CD}/boot/

# TODO: these move to os-kernel
pwd
ls dist/artifacts/vmlinuz-${KERNEL_VERSION}
cp ${ARTIFACTS}/vmlinuz-${KERNEL_VERSION}     ${CD}/boot/
#TODO cp ${ARTIFACTS}/linuxmods-${KERNEL_VERSION}   ${CD}/boot/

# cfg files creation moved to package-installer
DIST=$(pwd)/dist
cp -r ${DIST}/boot/* ${CD}/boot/
mkdir -p ${CD}/boot/grub
cat scripts/grub.cfg | envsubst > ${CD}/boot/grub/grub.cfg

cp /usr/lib/ISOLINUX/isolinux.bin              ${CD}/boot/isolinux/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32  ${CD}/boot/isolinux/
cp /usr/lib/syslinux/modules/bios/*.c32        ${CD}/boot/isolinux/
# add the installer image to the iso for non-network / dev/test
cp ${ARTIFACTS}/installer.tar                  ${CD}/rancheros/
cp ${ARTIFACTS}/Dockerfile.${ARCH}             ${CD}/rancheros/
gzip ${CD}/rancheros/installer.tar
cd ${CD} && \
    grub-mkrescue -o $ISO ${CD} -- -volid BurmillaOS -joliet on && \
    [ -e $ISO ] # grub-mkrescue doesn't exit non-zero on failure

cd $(dirname $ISO)
