#!/bin/bash
set -e
set -x

source $(dirname $0)/version
cd $(dirname $0)/..

ASSETS=$(pwd)/assets
ARTIFACTS=$(pwd)/dist/artifacts
CD=${BUILD}/cd
rm -rf ${CD}/
ISO=${ARTIFACTS}/$(echo ${DISTRIB_ID} | tr '[:upper:]' '[:lower:]').iso

mkdir -p ${CD}/rancheros
mkdir -p ${CD}/boot
cp ${ARTIFACTS}/${INITRD}                     ${CD}/boot/

# TODO: these move to os-kernel
pwd
ls dist/artifacts/vmlinuz-${KERNEL_VERSION}
cp ${ARTIFACTS}/vmlinuz-${KERNEL_VERSION}     ${CD}/boot/vmlinuz-${VERSION}
#TODO cp ${ARTIFACTS}/linuxmods-${KERNEL_VERSION}   ${CD}/boot/

# Include EFI files
DIST=$(pwd)/dist
mkdir -p ${CD}/EFI/boot
mkdir -p ${CD}/EFI/boot/drivers_x64
cp /$(pwd)/scripts/refin*.conf ${CD}/EFI/boot/
cp /usr/share/refind/refind/refind_x64.efi ${CD}/EFI/boot/
cp /usr/share/refind/refind/drivers_x64/iso9660_x64.efi ${CD}/EFI/boot/drivers_x64/

# add the installer image to the iso for non-network / dev/test
cp ${ARTIFACTS}/installer.tar                  ${CD}/rancheros/
cp ${ARTIFACTS}/Dockerfile.${ARCH}             ${CD}/rancheros/
gzip ${CD}/rancheros/installer.tar

# Prepare a FAT filesystem image and populate it with the
# EFI boot files....
cd ${CD}
dd if=/dev/zero of=refind.img bs=1024 count=5120
mkdosfs -n "ESP" refind.img
mcopy -irefind.img -s EFI ${ASSETS}/shellx64.efi ::/

# Make the ISO-9660 image file....
mkisofs -V "BurmillaOS" \
    -J -r -v -o $ISO \
    -eltorito-alt-boot -efi-boot refind.img \
    -no-emul-boot .

cd $(dirname $ISO)

